services:
  db:
    image: postgres:16-alpine
    container_name: carteira_postgres
    restart: always
    environment:
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_password
      POSTGRES_DB: finance_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finance_user -d finance_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance_net

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: carteira_backend
    restart: always
    ports:
      - "8010:8000"
    environment:
      - DATABASE_URL=postgresql://finance_user:finance_password@db:5432/finance_db
      - SECRET_KEY=carteira-digital-producao-secret-key-super-segura
      - ACCESS_TOKEN_EXPIRE_MINUTES=43200
    depends_on:
      db:
        condition: service_healthy
    networks:
      - finance_net

  frontend:
    build:
      context: ./finance-frontend
      dockerfile: Dockerfile
    container_name: carteira_frontend
    restart: always
    ports:
      - "3005:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://192.168.100.9:8010
    depends_on:
      - api
    networks:
      - finance_net

networks:
  finance_net:
    driver: bridge

volumes:
  postgres_data: